### ISSUE TITLE
No pic

### ISSUE THREAD

**Issue by tomatos666** [gvandela/MeteorRpiReceiver#2]
I recieve this error:
GRC script ended with return code: 2
What it means?

**Comment by gvandela** [comment]
The GRC (gnuradio companion) script handles the SDR stuff. You can launch this manually (it's a python script) to see if you get any more debug information. I would suspect there are some uninstalled dependencies.
Preparing a list of instructions starting from a fresh raspbian is on my todo list. I believe it doesn't extend further than gnuradio and gr-osmosdr. Did you install these?

**Comment by tomatos666** [comment]
I have installet the gnuradio and gr-osmosdr.
And it start the script wenn the elevation and azimtuh are positive. Bud after satelite passes it come´s follow:
2017-12-11 10:30:52,305 - root - DEBUG - stopping GRC script
2017-12-11 10:30:52,307 - root - DEBUG - GRC script ended with return code: 2
2017-12-11 10:31:12,324 - root - DEBUG - decoding: no recent file was found
2017-12-11 10:31:12,325 - root - DEBUG - no e-mail sent as there was no decoded image
2017-12-11 10:31:12,326 - root - DEBUG - all done, start over for next pass
2017-12-11 10:31:12,326 - root - DEBUG - trying TLE download...
2017-12-11 10:31:12,890 - root - DEBUG - Download successful, storing TLE file offline
2017-12-11 10:31:12,891 - root - DEBUG - TLE file downloaded & saved 11/12/17 10:31
It dosnt find some file... Bud i don´t know what if wrong...

**Comment by gvandela** [comment]
The line saying "decoding: no recent file was found" simply means that the gnuradio script did not produce any 'recording' (like a raw file with soft decoded data). This combined with the line saying "GRC script ended with return code: 2" indicates the gnuradio script is not doing what it's supposed to.
Can you launch the GRC script separately and log any error messages?

**Comment by tomatos666** [comment]
Hello,
yes bud there is no error:
pi@raspberrypi:~/MeteorRpiReceiver/GRC $ python METEOR_M2_v04_noGUI.py
linux; GNU C++ version 4.9.1; Boost_105500; UHD_003.007.003-0-unknown

gr-osmosdr 0.1.3 (0.1.3) gnuradio 3.7.5
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Elonics E4000 tuner
Using Volk machine: neon_hardfp_orc
Press Enter to quit:
You have new mail in /var/mail/pi

**Comment by tomatos666** [comment]
Hello,
I have changed some script´s what i have made.
Now have now the follow error:
2017-12-12 23:14:10,686 - root - DEBUG - stopping GRC script
2017-12-12 23:14:10,687 - root - DEBUG - GRC script ended with return code: 0
2017-12-12 23:14:30,799 - root - DEBUG - running: ./Decoder/medet_arm /home/pi/Projects/Pyt$
/bin/sh: 1: ./Decoder/medet_arm: Permission denied

**Comment by tomatos666** [comment]
2017-12-13 11:29:49,390 - root - DEBUG - stopping GRC script
2017-12-13 11:29:49,609 - root - DEBUG - GRC script ended with return code: 1
2017-12-13 11:30:09,637 - root - DEBUG - running: ./Decoder/medet_arm /home/pi/Projects/Python_projects/Meteor_receiver/Data/meteor_LRPT_13122017_1116.s /home/pi/Projects/Python_projects/Meteor_receiver/Data/meteor_LRPT_13122017_1116 -Q
2017-12-13 11:30:39,200 - root - DEBUG - medet ran with returncode: 0
Traceback (most recent call last):
  File "scheduler_v0.2.8.py", line 352, in <module>
    file_name = decode_capture()        # since we don't know what file name the GRC script generated, we look for a file generated in the last 30min
  File "scheduler_v0.2.8.py", line 162, in decode_capture
    mod_time = getmtime(join(mypath, file))
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/home/pi/Projects/Python_projects/Meteor_receiver/Data/meteor_LRPT_13122017_0935.s'

**Comment by tomatos666** [comment]
Hello,
now i recieve every time "No Raw file found" what can i do?

**Comment by gvandela** [comment]
Hi,
Can you check if you get .bmp files in the Data folder? Or the decoder is not producing any bitmaps, or the filename and/or directory is wrong...

**Comment by tomatos666** [comment]
Hello,
thanks for your answer. The directora are the folling /home/pi/Projects/Python_projects/Meteor_receiver/Decoder and are no bitmaps on the folder Images

**Comment by tomatos666** [comment]
I hope you can help me

**Comment by gvandela** [comment]
Hi,
After staring at the logs you posted, it seems like it's trying to handle a file that was deleted already. Which would mean that files can appear double in 'onlyfiles' in 'def decode_capture()'.
Before we try and fix this, please comment out line 188:
`os.remove(os.path.join(mypath, file))`

**Comment by tomatos666** [comment]
Hello, i have commet out the line 188.
Now the files are still in the folder Data. Bud no pic´s.

**Comment by tomatos666** [comment]
Hello, i have try it manualy do decode the .s file. Bud it dosnt converd somthing.
I have try it do convert the .s files on a  windows PC with the medet for windows. Bud it dosnt generate any file. I don´t know why...

**Comment by gvandela** [comment]
Do you have a .s file generated by someone else that has been confirmed to decode? I'll see if I can make one available for download. You might have some problems with your hardware maybe. Like your antenna (or preamplifier if you use one, though the dvb-t sticks do quite well without). Or even coaxial cables or connectors.

**Comment by gvandela** [comment]
Here's a link to a small size .s file. It decodes to a couple of lines of image, really small, but should be useful to confirm the issue is with the .s files your setup generates.
[Meteor M2 test .s file](http://gofile.me/37bNJ/d7GPeRXQt
)

**Comment by tomatos666** [comment]
Hello, thank you for your answer. 
Your file work fine. Bud my file´s dosn´t work. Here is a link to my Files [Folder Data with Noaa](https://www.dropbox.com/sh/30uhs9c0grgn80l/AADmc4oAnRWnwofapa4LzyKTa?dl=0) Also are pic´s for NOAA what are generatet with the same hardware.
I use a Raspberry RPI3 with a Terratec Cinergy T Stick RC (Rev.3) and a QFH Antenna.

**Comment by gvandela** [comment]
Huh, and that setup actually works for NOAA APT?! I don't see how it shouldn't work for Meteor LRPT... I'll see if I can make a version of the GRC script with a GUI, to get some visual feedback. I didn't do that because it's wasted computing power on a headless setup.

**Comment by tomatos666** [comment]
Hello gvandela, can you tell me please what typ of hardware you use?

**Comment by gvandela** [comment]
I'm running the script on a raspberry pi 3 model B, with Nooelec RTL stick. The antenna is a quadrifilar helix of my own design, but close to identical as many QFH antenna designs on the Web. I use no external LNA nor filter. The antenna is positioned in my attic which gives much better reception than my office just underneath. The RTL USB stick is attached very close to the antenna feed point, with a 5m USB cable to the raspberry pi. This to avoid losses of a run of coax cable.
